name: Python CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from repository
    - name: check out code    
      uses: actions/checkout@v4
    # Step2: Set up python environment

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    # Step3: Install dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
       
    # Step4 : Run Tests
    - name: Run Tests
      run: pytest
